### ISSUE TITLE
Unable to handle files more than 150 kb 

### ISSUE THREAD

**Issue by ultrainstintgoku** [oxen-io/session-file-server#3]
Hi Team ,
I tried to host my own file server to handle our session network devices . but the files larger than 150 kb is getting failed . 
I haven't changed the file . it is with the default handling size of 6 mb 
8 mb after base 64 and 10 mb .

**Comment by jagerman** [comment]
I don't know what your setup is, but if it's nginx you likely need to add `client_max_body_size 10M;` into the front-end proxy site config file.

**Comment by ultrainstintgoku** [comment]
@jagerman . 
Thank you for suggestion 
I have configured with the size as you have mentioned . still i am facing the issue 
is anything else i have to look into
